ALTER TABLE `${PROJECT_ID}.${DATASET}.tracked_keywords`
ADD COLUMN IF NOT EXISTS pillar STRING;

ALTER TABLE `${PROJECT_ID}.${DATASET}.tracked_keywords`
ADD COLUMN IF NOT EXISTS cluster STRING;

ALTER TABLE `${PROJECT_ID}.${DATASET}.tracked_keywords`
ADD COLUMN IF NOT EXISTS intent STRING;
