#!/usr/bin/env bash
set -euo pipefail

required_vars=(
  GOOGLE_CLOUD_PROJECT
  CLOUD_RUN_REGION
  ARTIFACT_REGISTRY_REPOSITORY
  CRAWL_INTERNAL_LINKS_JOB_NAME
  CRAWL_INTERNAL_LINKS_JOB_SERVICE_ACCOUNT
  BIGQUERY_DATASET
  TARGET_SITE_HOST
)

for required_var in "${required_vars[@]}"; do
  if [[ -z "${!required_var:-}" ]]; then
    echo "Missing required environment variable: ${required_var}" >&2
    exit 1
  fi
done

CRAWL_INTERNAL_LINKS_IMAGE_NAME="${CRAWL_INTERNAL_LINKS_IMAGE_NAME:-crawl-internal-links-job}"
CRAWL_INTERNAL_LINKS_IMAGE_TAG="${CRAWL_INTERNAL_LINKS_IMAGE_TAG:-latest}"
BIGQUERY_LOCATION="${BIGQUERY_LOCATION:-asia-northeast1}"
CRAWL_INTERNAL_LINKS_JOB_CPU="${CRAWL_INTERNAL_LINKS_JOB_CPU:-1}"
CRAWL_INTERNAL_LINKS_JOB_MEMORY="${CRAWL_INTERNAL_LINKS_JOB_MEMORY:-512Mi}"
CRAWL_INTERNAL_LINKS_JOB_TIMEOUT="${CRAWL_INTERNAL_LINKS_JOB_TIMEOUT:-1800s}"
CRAWL_INTERNAL_LINKS_JOB_MAX_RETRIES="${CRAWL_INTERNAL_LINKS_JOB_MAX_RETRIES:-1}"
CRAWL_INTERNAL_LINKS_JOB_TASKS="${CRAWL_INTERNAL_LINKS_JOB_TASKS:-1}"
CRAWL_INTERNAL_LINKS_JOB_PARALLELISM="${CRAWL_INTERNAL_LINKS_JOB_PARALLELISM:-1}"
CRAWL_INTERNAL_LINKS_DEFAULT_ARGS="${CRAWL_INTERNAL_LINKS_DEFAULT_ARGS:-}"
CRAWL_INTERNAL_LINKS_SECRET_MAPPINGS="${CRAWL_INTERNAL_LINKS_SECRET_MAPPINGS:-}"
CRAWL_INTERNAL_LINKS_START_URL="${CRAWL_INTERNAL_LINKS_START_URL:-}"
CRAWL_INTERNAL_LINKS_USER_AGENT="${CRAWL_INTERNAL_LINKS_USER_AGENT:-}"

IMAGE_URI="${CLOUD_RUN_REGION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${ARTIFACT_REGISTRY_REPOSITORY}/${CRAWL_INTERNAL_LINKS_IMAGE_NAME}:${CRAWL_INTERNAL_LINKS_IMAGE_TAG}"

gcloud builds submit \
  --project="${GOOGLE_CLOUD_PROJECT}" \
  --config="cloudbuild.crawl-internal-links.yaml" \
  --substitutions="_IMAGE_URI=${IMAGE_URI}" \
  .

env_vars=(
  "GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}"
  "BIGQUERY_DATASET=${BIGQUERY_DATASET}"
  "BIGQUERY_LOCATION=${BIGQUERY_LOCATION}"
  "TARGET_SITE_HOST=${TARGET_SITE_HOST}"
)

if [[ -n "${CRAWL_INTERNAL_LINKS_START_URL}" ]]; then
  env_vars+=("INTERNAL_LINKS_START_URL=${CRAWL_INTERNAL_LINKS_START_URL}")
fi

if [[ -n "${CRAWL_INTERNAL_LINKS_USER_AGENT}" ]]; then
  env_vars+=("INTERNAL_LINKS_USER_AGENT=${CRAWL_INTERNAL_LINKS_USER_AGENT}")
fi

deploy_args=(
  run jobs deploy "${CRAWL_INTERNAL_LINKS_JOB_NAME}"
  --project="${GOOGLE_CLOUD_PROJECT}"
  --region="${CLOUD_RUN_REGION}"
  --image="${IMAGE_URI}"
  --service-account="${CRAWL_INTERNAL_LINKS_JOB_SERVICE_ACCOUNT}"
  --tasks="${CRAWL_INTERNAL_LINKS_JOB_TASKS}"
  --parallelism="${CRAWL_INTERNAL_LINKS_JOB_PARALLELISM}"
  --max-retries="${CRAWL_INTERNAL_LINKS_JOB_MAX_RETRIES}"
  --task-timeout="${CRAWL_INTERNAL_LINKS_JOB_TIMEOUT}"
  --cpu="${CRAWL_INTERNAL_LINKS_JOB_CPU}"
  --memory="${CRAWL_INTERNAL_LINKS_JOB_MEMORY}"
  --set-env-vars="$(IFS=,; echo "${env_vars[*]}")"
)

if [[ -n "${CRAWL_INTERNAL_LINKS_DEFAULT_ARGS}" ]]; then
  deploy_args+=(--args="${CRAWL_INTERNAL_LINKS_DEFAULT_ARGS}")
fi

if [[ -n "${CRAWL_INTERNAL_LINKS_SECRET_MAPPINGS}" ]]; then
  deploy_args+=(--set-secrets="${CRAWL_INTERNAL_LINKS_SECRET_MAPPINGS}")
fi

gcloud "${deploy_args[@]}"
